CREATE TABLE notify (id int NOT NULL AUTO_INCREMENT, app_key varchar(50) COMMENT '供应商合作key', app_secret varchar(50) COMMENT '供应商合作value', notify_url varchar(200) COMMENT '通知地址', notify_type varchar(50) NOT NULL COMMENT '通知类型', third_type varchar(10) NOT NULL COMMENT '第三方类型', PRIMARY KEY (id), INDEX product_audit_notify_APP (app_key, app_secret)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE order_to_third_ota (id int NOT NULL AUTO_INCREMENT COMMENT '主键', vendorOrderId varchar(100) COMMENT '供应商订单号', thirdOrderId varchar(100) COMMENT '第三方订单号', sn varchar(50) NOT NULL, third_type varchar(50) COMMENT '第三方类型', interface_name varchar(100) COMMENT '接口名称', real_action varchar(50) NOT NULL COMMENT '供应商真实的动作', request_xml longtext COMMENT '请求报文', response_xml longtext COMMENT '返回报文', request_time datetime COMMENT '请求时间', response_time datetime COMMENT '返回时间', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存平台到第三方或者第三方到平台的订单报文';
CREATE TABLE order_to_top (id int NOT NULL AUTO_INCREMENT COMMENT '主键', vendorOrderId varchar(100) COMMENT '供应商订单号', thirdOrderId varchar(100) COMMENT '第三方订单号', sn varchar(50) NOT NULL, third_type varchar(50) COMMENT '第三方类型', interface_name varchar(100) COMMENT '接口名称', real_action varchar(50) NOT NULL COMMENT '供应商真实的动作', request_xml longtext COMMENT '请求报文', response_xml longtext COMMENT '返回报文', request_time datetime COMMENT '请求时间', response_time datetime COMMENT '返回时间', PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='存从平台到供应商或者供应商到平台的报文';
CREATE TABLE product_audit_content (id int NOT NULL AUTO_INCREMENT, product_code varchar(100) NOT NULL COMMENT '产品编码', request_xml longtext COMMENT '第三方返回的报文', app_key varchar(50) COMMENT '供应商key', app_secret varchar(50) COMMENT '供应商value', is_notify char(1) DEFAULT 'N' COMMENT '是否已通知供应商 Y-已通知 N-未通知', request_time datetime COMMENT '携程请求时间', send_success_time datetime COMMENT '成功发送到供应商系统时间', PRIMARY KEY (id), INDEX ProductAuditContent_appKeyIDX (app_key), INDEX ProductAuditContent_AppSecretIDX (app_secret), INDEX ProductAuditConten_IsNotifyIDX (is_notify)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE product_to_third_ota (id int NOT NULL AUTO_INCREMENT, product_code varchar(100) NOT NULL COMMENT '产品编码', ota_type varchar(20) NOT NULL COMMENT 'ota平台类型', request_xml longtext COMMENT '请求报文', response_xml longtext COMMENT '返回报文', request_time datetime COMMENT '请求时间', response_time datetime COMMENT '返回时间', interface_name varchar(100) COMMENT '接口名称', real_action varchar(50) NOT NULL COMMENT '供应商真实的动作', SN varchar(40) NOT NULL COMMENT '处理流水号', PRIMARY KEY (id), INDEX product_to_third_OTASN_IDX (SN)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE product_to_top (id int NOT NULL AUTO_INCREMENT, product_code varchar(100) COMMENT '产品编码', appkey varchar(50) NOT NULL COMMENT 'top平台合作key', appSecret varchar(50) NOT NULL COMMENT 'top平台合作密钥', SN varchar(40) NOT NULL COMMENT '处理流水号', request_xml longtext COMMENT '请求报文', response_xml longtext COMMENT '返回报文', request_time datetime COMMENT '请求时间', response_time datetime COMMENT '返回时间', real_action varchar(50) NOT NULL COMMENT '供应商真实的动作 A-添加 U-更新', PRIMARY KEY (id), CONSTRAINT product_to_topSN_IDX UNIQUE (SN)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.135:8082/orderB2bOpen/ctripOrderCreate.htm', 'Ctrip-Order-Create', 'CTRIP');
INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.135:8082/orderB2bOpen/otaOrderDeal.htm', 'Ctrip-Order-Update', 'CTRIP');
INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.135:8082/orderB2bOpen/otaOrderDeal.htm', 'Ctrip-Order-Cancle', 'CTRIP');
INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.112:8080/drolay/common/share/cancleOrDeleteShareOrder.in', 'Ctrip-Order-Delete', 'CTRIP');
INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.135:8080/ctripAuditProduct.htm', 'Ctrip-Product-Audit', 'CTRIP');
INSERT INTO notify (app_key, app_secret, notify_url, notify_type, third_type) VALUES ('9001', '9001', 'http://192.168.79.135:8082/orderB2bOpen/otaOrderDeal.htm', 'Ctrip-Order-Pay', 'CTRIP');
